[package]
name = "dotm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
youchoose = "0.1.1"
whoami = "1.2.1"
colored = "2.0.0"