#! /usr/bin/python

import sys
import configparser
from os import (makedirs, path)
import getpass

username = getpass.getuser()


args = sys.argv[1:]

config = configparser.ConfigParser()

config['main'] = {'dotfiles_path': ""}

class Config:
  def __init__(self):
    self.config_file_path = f"/home/{username}/.config/dotm/dotm.conf"
    self.config_dir_path = f"/home/{username}/.config/dotm/"
  
  def config_file_exists(self):
    file_exists = path.exists(self.config_file_path)
    if not file_exists: return False

    return True
  
  def config_dir_exists(self):
    dir_exists = path.exists(self.config_dir_path)
    if not dir_exists: return False

    return True

  def create_file(self): 
    if not self.config_dir_exists(): self.create_dir()
    if self.config_file_exists():
      answer  = str(input("You are going to overwrite your configuration, Do you want to continue [yes/no] : "))
      if answer == 'no' or answer == 'n': return

    with open(self.config_file_path, 'w') as configfile:
      config.write(configfile)
    configfile.close()
    print("[+] Config file '% s' created" % self.config_file_path)

  def create_dir(self): 
    if self.config_dir_exists(): return
    makedirs(self.config_dir_path)
    print("Directory '% s' created" % self.config_dir_path)


def help():
  print("--help, -h\t help message")
  print("--create, -C\t create new config file")

def init(): 
  print("what is dotfiles dir path: ")
  dotfiles_path = str(input(": "))

def main(): 
  if "--help" in args or "-h" in args:
    help()
    exit(0)
  Config().create_file()

if __name__ == "__main__":
  main()

